CREATE OR REPLACE FUNCTION set_updated_time()
RETURNS TRIGGER AS
$$
BEGIN
	NEW.updated_at = NOW();
	RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TABLE users (
	id BIGSERIAL PRIMARY KEY,
	username VARCHAR(20) NOT NULL,
	email VARCHAR(255) UNIQUE NOT NULL,
	password_hash TEXT,
	created_at TIMESTAMPTZ DEFAULT NOW(),
	updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TRIGGER update_users_updated_at
BEFORE UPDATE ON users
FOR EACH ROW
EXECUTE FUNCTION set_updated_time();
